# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Listing
      run: ls
    - name: Pack
      run: dotnet pack ./library --configuration Release
    - name: Publish
      run: dotnet nuget push "./library/bin/Release/kasza-lehel.1.0.1.nupkg"  --api-key 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 --source "https://nuget.pkg.github.com/LehelKasza/index.json"
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 6.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
