name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: alirezanet/publish-nuget@v3.1.x
        with:
          PROJECT_FILE_PATH: KL.csproj
